workflows:
  ios-release:
    name: iOS Release
    platform: ios
    macos: true
    xcode: "12.5"  # تحديد إصدار Xcode المناسب
    scripts:
      - name: Install Dependencies
        script: |
          npm install -g cordova
          npm install -g ionic
          npm install
      - name: Build Cordova Project
        script: |
          ionic cordova build ios --prod --release
    artifacts:
      - build/platforms/ios/build/device/*.ipa  # المسار الذي سيتم حفظ الـ IPA فيه بعد البناء
