workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60 # الحد الأقصى لوقت البناء (دقائق)
    environment:
      vars:
        BUILD_TYPE: "Release"
    scripts:
      - name: Install Dependencies
        script: |
          npm install -g cordova
          npm install -g ionic
          npm install
      - name: Check for errors
        script: |
          tail -n 20 /var/log/codemagic.log
    artifacts:
      - build/platforms/ios/build/device/*.ipa  # المسار الذي سيتم حفظ الـ IPA فيه بعد البناء
